# Generated by Django 4.0.2 on 2022-02-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_alter_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTTArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
